# docker-compose-dev.yml
services:
  app-1:
    image: otboo:local
    build:
      context: .
      dockerfile: Dockerfile
    container_name: otboo-app-1
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - INSTANCE_ID=app-1

      - SPRING_ELASTICSEARCH_URIS=${SPRING_ELASTICSEARCH_URIS}
      - SPRING_ELASTICSEARCH_USERNAME=${SPRING_ELASTICSEARCH_USERNAME}
      - SPRING_ELASTICSEARCH_PASSWORD=${SPRING_ELASTICSEARCH_PASSWORD}

      - JWT_SECRET=${JWT_SECRET}
      - ACCESS_TOKEN_EXPIRATION=${ACCESS_TOKEN_EXPIRATION}
      - REFRESH_TOKEN_EXPIRATION=${REFRESH_TOKEN_EXPIRATION}
      - ISSUER=${ISSUER}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_REGION=${AWS_REGION}
      - KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}
      - KMA_API_KEY=${KMA_API_KEY}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

      - NAVER_MAIL_ID=${NAVER_MAIL_ID}
      - NAVER_MAIL_PASSWORD=${NAVER_MAIL_PASSWORD}

      - KAFKA_API_KEY=${KAFKA_API_KEY}
      - KAFKA_API_SECRET=${KAFKA_API_SECRET}

      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

      - SECURE=${SECURE}
      - SAMESITE=${SAMESITE}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${SPRING_KAFKA_BOOTSTRAP_SERVERS}

    depends_on:
      - redis
      - es
      - kafka
    restart: on-failure

  app-2:
    image: otboo:local
    build:
      context: .
      dockerfile: Dockerfile
    container_name: otboo-app-2
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - INSTANCE_ID=app-2

      - SPRING_ELASTICSEARCH_URIS=${SPRING_ELASTICSEARCH_URIS}
      - SPRING_ELASTICSEARCH_USERNAME=${SPRING_ELASTICSEARCH_USERNAME}
      - SPRING_ELASTICSEARCH_PASSWORD=${SPRING_ELASTICSEARCH_PASSWORD}

      - JWT_SECRET=${JWT_SECRET}
      - ACCESS_TOKEN_EXPIRATION=${ACCESS_TOKEN_EXPIRATION}
      - REFRESH_TOKEN_EXPIRATION=${REFRESH_TOKEN_EXPIRATION}
      - ISSUER=${ISSUER}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_REGION=${AWS_REGION}
      - KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}
      - KMA_API_KEY=${KMA_API_KEY}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

      - NAVER_MAIL_ID=${NAVER_MAIL_ID}
      - NAVER_MAIL_PASSWORD=${NAVER_MAIL_PASSWORD}

      - KAFKA_API_KEY=${KAFKA_API_KEY}
      - KAFKA_API_SECRET=${KAFKA_API_SECRET}

      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

      - SECURE=${SECURE}
      - SAMESITE=${SAMESITE}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    depends_on:
      - redis
      - es
      - kafka
    restart: on-failure

  es:
    build:
      context: .
      dockerfile: elasticsearch/elasticsearch.Dockerfile
    container_name: otboo-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.3
    container_name: otboo-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - "5601:5601"
    depends_on:
      - es

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  es-data:
    driver: local
  redis-data:
    driver: local